"""Traduz main.py e os dados do banco de Espanhol para Português Brasil."""
import re, psycopg2

DB_CONFIG = dict(host="localhost", database="granja_db", user="postgres", password="password")

# ── Substituições em main.py ──────────────────────────────────────────────────
# Ordem importa: mais específicas primeiro para evitar substituições parciais.
TEXT_MAP = [
    # ── Constantes / listas ───────────────────────────────────────────────
    ('"Vacunación"',                    '"Vacinação"'),
    ('"Control rutinario"',             '"Controle rotineiro"'),
    ('"Tratamiento"',                   '"Tratamento"'),
    ('"Enfermedad"',                    '"Doença"'),
    ('"Parto asistido"',                '"Parto assistido"'),
    ('"Cirugía"',                       '"Cirurgia"'),
    ('"Tractor"',                       '"Trator"'),
    ('"Ordeñadora"',                    '"Ordenhadeira"'),
    ('"Compresor"',                     '"Compressor"'),
    ('"Generador"',                     '"Gerador"'),
    ('"Cargadora"',                     '"Carregadeira"'),
    ('"Otro"',                          '"Outro"'),
    ('"Correctivo"',                    '"Corretivo"'),
    ('"Cambio de aceite"',              '"Troca de óleo"'),
    ('"Revisión general"',              '"Revisão geral"'),
    ('"Reparación"',                    '"Reparo"'),
    ('"Calibración"',                   '"Calibração"'),
    ('"Operativa"',                     '"Operacional"'),
    ('"En mantenimiento"',              '"Em manutenção"'),
    ('"Fuera de servicio"',             '"Fora de serviço"'),
    ('"Inseminación Artificial"',       '"Inseminação Artificial"'),
    ('"Exitoso"',                       '"Bem-sucedido"'),
    ('"Gemelar"',                       '"Gemelar"'),
    ('"Cría muerta"',                   '"Cria morta"'),
    ('"Ordeñador/a"',                   '"Ordenhador/a"'),
    ('"Tractorista"',                   '"Tratorista"'),
    ('"Encargado/a de alimentación"',   '"Resp. por alimentação"'),
    ('"Encargado/a de sanidad"',        '"Resp. por sanidade"'),
    ('"Veterinario/a de campo"',        '"Veterinário/a de campo"'),
    ('"Peón rural"',                    '"Trabalhador rural"'),
    ('"Sueldo"',                        '"Salário"'),
    ('"Adelanto"',                      '"Adiantamento"'),
    ('"Bono"',                          '"Bônus"'),
    ('"Liquidación"',                   '"Rescisão"'),
    ('"Venta de leche"',                '"Venda de leite"'),
    ('"Venta de animales"',             '"Venda de animais"'),
    ('"Subsidio o ayuda estatal"',      '"Subsídio ou apoio estatal"'),
    ('"Otro ingreso"',                  '"Outra receita"'),
    ('"Alimentación e insumos"',        '"Alimentação e insumos"'),
    ('"Veterinario y salud animal"',    '"Veterinário e saúde animal"'),
    ('"Mantenimiento de maquinaria"',   '"Manutenção de maquinário"'),
    ('"Mano de obra"',                  '"Mão de obra"'),
    ('"Combustible"',                   '"Combustível"'),
    ('"Servicios (luz, agua, gas)"',    '"Serviços (luz, água, gás)"'),
    ('"Otros gastos"',                  '"Outros gastos"'),
    # single-quote versions (SQL WHERE, etc. — só as que estão fora do SQL real)
    ("'Vacunación'",                    "'Vacinação'"),
    ("'Control rutinario'",             "'Controle rotineiro'"),
    ("'Tratamiento'",                   "'Tratamento'"),
    ("'Enfermedad'",                    "'Doença'"),
    ("'Parto asistido'",                "'Parto assistido'"),
    ("'Cirugía'",                       "'Cirurgia'"),
    ("'Operativa'",                     "'Operacional'"),
    ("'En mantenimiento'",              "'Em manutenção'"),
    ("'Fuera de servicio'",             "'Fora de serviço'"),
    ("'Exitoso'",                       "'Bem-sucedido'"),
    ("'Sueldo'",                        "'Salário'"),
    ("'Adelanto'",                      "'Adiantamento'"),
    ("'Bono'",                          "'Bônus'"),
    ("'Ingreso'",                       "'Receita'"),
    ("'Egreso'",                        "'Despesa'"),
    ("'activa'",                        "'ativa'"),
    ("'inactiva'",                      "'inativa'"),
    ("'activo'",                        "'ativo'"),
    ("'inactivo'",                      "'inativo'"),
    ("'Fertilización'",                 "'Fertilização'"),
    # ── Constante ELEGIR ──────────────────────────────────────────────────
    ('"— Elegí una opción —"',          '"— Escolha uma opção —"'),
    # ── Navegación ───────────────────────────────────────────────────────
    ('"🏠 Inicio"',       '"🏠 Início"'),
    ('"💊 Salud"',        '"💊 Saúde"'),
    ('"🥛 Leche"',        '"🥛 Leite"'),
    ('"📦 Bodega"',       '"📦 Estoque"'),
    ('"🚜 Maquinaria"',   '"🚜 Maquinário"'),
    ('"🐣 Reproducción"', '"🐣 Reprodução"'),
    ('"💰 Finanzas"',     '"💰 Finanças"'),
    ('"👷 Empleados"',    '"👷 Funcionários"'),
    ('"📊 Reportes"',     '"📊 Relatórios"'),
    # ── Helper texts ──────────────────────────────────────────────────────
    ('"Los campos marcados con * son obligatorios."',
     '"Os campos marcados com * são obrigatórios."'),
    ('"Todavía no hay registros aquí."',
     '"Ainda não há registros aqui."'),
    ('f"No se pudo guardar. Revisá los datos e intentá de nuevo.\\n(Detalle: {exc})"',
     'f"Não foi possível salvar. Verifique os dados e tente novamente.\\n(Detalhe: {exc})"'),
    # ── Dashboard ─────────────────────────────────────────────────────────
    ('"Resumen General"',       '"Resumo Geral"'),
    ('"Así está tu granja hoy."', '"Veja como está sua fazenda hoje."'),
    ('"⚠  Alertas que necesitan tu atención"',
     '"⚠  Alertas que precisam de atenção"'),
    ('f"💊  {vacas_tratamiento} animal{\'es\' if vacas_tratamiento != 1 else \'\'} en tratamiento esta semana — revisá Salud."',
     'f"💊  {vacas_tratamiento} animal{\'is\' if vacas_tratamiento != 1 else \'\'} em tratamento esta semana — veja Saúde."'),
    ('f"📦  Stock crítico: {row[\'nombre_insumo\']} — quedan {row[\'stock_actual_kg\']:.0f} kg"',
     'f"📦  Estoque crítico: {row[\'nombre_insumo\']} — restam {row[\'stock_actual_kg\']:.0f} kg"'),
    ('"¡Hoy!"',           '"Hoje!"'),
    ('f"¡En {dias} día{\'s\' if dias != 1 else \'\'}!"',
     'f"Em {dias} dia{\'s\' if dias != 1 else \'\'}!"'),
    ('f"En {dias} días"', 'f"Em {dias} dias"'),
    ('f"🐣  Parto de {row[\'nombre\']} — {txt} ({row[\'fecha_parto_esperado\']})"',
     'f"🐣  Parto de {row[\'nombre\']} — {txt} ({row[\'fecha_parto_esperado\']})"'),
    ('f"🚜  Mantenimiento vencido: {row[\'nombre\']} (vencía {row[\'proximo_mantenimiento\']})"',
     'f"🚜  Manutenção vencida: {row[\'nombre\']} (venceu em {row[\'proximo_mantenimiento\']})"'),
    ('"🐄 Vacas Activas"',   '"🐄 Vacas Ativas"'),
    ('"en producción"',      '"em produção"'),
    ('"Ver →"',              '"Ver →"'),
    ('"🥛 Litros Hoy"',      '"🥛 Litros Hoje"'),
    ('f"↑ {_dif_litros:+.0f} L vs ayer"', 'f"↑ {_dif_litros:+.0f} L vs ontem"'),
    ('f"↓ {_dif_litros:.0f} L vs ayer"',  'f"↓ {_dif_litros:.0f} L vs ontem"'),
    ('"📈 L/Vaca/Día"',      '"📈 L/Vaca/Dia"'),
    ('"eficiencia hoy"',     '"eficiência hoje"'),
    ('"Ver reportes →"',     '"Ver relatórios →"'),
    ('"💊 En Tratamiento"',  '"💊 Em Tratamento"'),
    ('"últimos 7 días"',     '"últimos 7 dias"'),
    ('"Ver salud →"',        '"Ver saúde →"'),
    ('"💰 Balance Mes"',     '"💰 Balanço do Mês"'),
    ('"ingresos – egresos"', '"receitas – despesas"'),
    ('"Ver finanzas →"',     '"Ver finanças →"'),
    ('"No se pudo conectar a la base de datos. Avisá al administrador."',
     '"Não foi possível conectar ao banco de dados. Avise o administrador."'),
    ('"Acciones frecuentes"', '"Ações frequentes"'),
    ('"Registrar ordeñe"',    '"Registrar ordenha"'),
    ('"Anotar evento de salud"', '"Registrar evento de saúde"'),
    ('"Reponer stock"',       '"Repor estoque"'),
    ('"Registrar mantenimiento"', '"Registrar manutenção"'),
    ('"Registrar fertilización"', '"Registrar fertilização"'),
    ('"Stock de insumos (kg)"', '"Estoque de insumos (kg)"'),
    ('"Cuánto hay en bodega de cada alimento o producto."',
     '"Quanto há em estoque de cada alimento ou produto."'),
    ('"Producción de leche — últimos 7 días"', '"Produção de leite — últimos 7 dias"'),
    ('"Litros totales por día en la última semana."',
     '"Litros totais por dia na última semana."'),
    ('"Vacas por grupo"', '"Vacas por grupo"'),
    ('"Distribución de animales según su grupo de alimentación."',
     '"Distribuição de animais por grupo de alimentação."'),
    ('"Sin datos de stock aún."',
     '"Sem dados de estoque ainda."'),
    ('"Andá a Bodega para cargar insumos."',
     '"Vá a Estoque para cadastrar insumos."'),
    ('"Sin registros de leche aún."',
     '"Sem registros de leite ainda."'),
    ('"Andá a Leche para registrar ordeñes."',
     '"Vá a Leite para registrar ordenhas."'),
    ('"Sin grupos cargados aún."',
     '"Sem grupos cadastrados ainda."'),
    ('"Andá a Vacas para agregar animales."',
     '"Vá a Vacas para adicionar animais."'),
    # ── Vacas page ────────────────────────────────────────────────────────
    ('"🐄 Registro de Animales"',  '"🐄 Registro de Animais"'),
    ('"Acá podés ver todos tus animales y agregar nuevos al plantel."',
     '"Aqui você pode ver todos os seus animais e adicionar novos ao rebanho."'),
    ('"Animales por Grupo"',        '"Animais por Grupo"'),
    ('"Agregar un Animal"',         '"Adicionar um Animal"'),
    ('"Solo el Grupo es obligatorio. El nombre es un apodo o número para identificarlo fácilmente."',
     '"Somente o Grupo é obrigatório. O nome é um apelido ou número para identificar o animal com facilidade."'),
    ('"Grupo"',                     '"Grupo"'),
    ('"¿En qué grupo de alimentación va este animal?"',
     '"Em qual grupo de alimentação vai este animal?"'),
    ('"Nombre o Etiqueta"',         '"Nome ou Etiqueta"'),
    ('"Podés escribir un apodo, número o código. Si lo dejás vacío se asigna uno automático."',
     '"Você pode escrever um apelido, número ou código. Se deixar em branco, será atribuído automaticamente."'),
    ('"Ej: Manchita, #42, Oreja-Amarilla…"',
     '"Ex: Manchinha, #42, Orelha-Amarela…"'),
    ('"Primero elegí el grupo al que pertenece el animal."',
     '"Primeiro escolha o grupo ao qual pertence o animal."'),
    ('f"✓ {nombre_val} fue agregado al grupo \'{grupo.value}\'."',
     'f"✓ {nombre_val} foi adicionado ao grupo \'{grupo.value}\'."'),
    ('"➕  Agregar Animal"',       '"➕  Adicionar Animal"'),
    ('"Todos los Animales"',        '"Todos os Animais"'),
    ('"Todavía no hay animales en el sistema."',
     '"Ainda não há animais no sistema."'),
    ('"Usá el formulario de abajo para agregar el primero."',
     '"Use o formulário abaixo para adicionar o primeiro."'),
    ('"Ver ficha →"',               '"Ver ficha →"'),
    ('"Error al cargar grupos."',   '"Erro ao carregar grupos."'),
    ('"Error al cargar el listado."', '"Erro ao carregar a lista."'),
    # ── Salud page ────────────────────────────────────────────────────────
    ('"💊 Control Sanitario"',
     '"💊 Controle Sanitário"'),
    ('"Registrá cualquier atención veterinaria: vacunas, tratamientos o revisiones."',
     '"Registre qualquer atendimento veterinário: vacinas, tratamentos ou revisões."'),
    ('"No se pudo cargar la lista de animales. Avisá al administrador."',
     '"Não foi possível carregar a lista de animais. Avise o administrador."'),
    ('"Registrar Atención Veterinaria"',
     '"Registrar Atendimento Veterinário"'),
    ('"Completá el formulario con los datos del evento sanitario."',
     '"Preencha o formulário com os dados do evento sanitário."'),
    ('"Animal"',                     '"Animal"'),
    ('"¿Cuál animal fue atendido?"', '"Qual animal foi atendido?"'),
    ('"Tipo de evento"',             '"Tipo de evento"'),
    ('"¿Qué tipo de atención recibió?"', '"Que tipo de atendimento recebeu?"'),
    ('"Fecha"',                      '"Data"'),
    ('"¿Cuándo ocurrió?"',           '"Quando ocorreu?"'),
    ('"Veterinario"',                '"Veterinário"'),
    ('"Nombre del profesional que atendió (opcional)."',
     '"Nome do profissional que atendeu (opcional)."'),
    ('"Costo ($)"',                  '"Custo (R$)"'),
    ('"Costo total de la atención (opcional)."',
     '"Custo total do atendimento (opcional)."'),
    ('"Descripción"',                '"Descrição"'),
    ('"Describí qué pasó, tratamiento aplicado, evolución del animal…"',
     '"Descreva o que aconteceu, tratamento aplicado, evolução do animal…"'),
    ('"Primero elegí el animal."',   '"Primeiro escolha o animal."'),
    ('"Primero elegí el tipo de evento."', '"Primeiro escolha o tipo de evento."'),
    ('f"✓ {tipo_ev.value} registrado para {animal.value}."',
     'f"✓ {tipo_ev.value} registrado para {animal.value}."'),
    ('"💾  Guardar Atención"',       '"💾  Salvar Atendimento"'),
    ('"Historial Sanitario"',        '"Histórico Sanitário"'),
    ('"Todavía no hay eventos sanitarios registrados."',
     '"Ainda não há eventos sanitários registrados."'),
    ('"Usá el formulario de arriba para registrar el primero."',
     '"Use o formulário acima para registrar o primeiro."'),
    ('"Error al cargar historial."', '"Erro ao carregar histórico."'),
    # ── Leche page ────────────────────────────────────────────────────────
    ('"🥛 Registro de Leche"',       '"🥛 Registro de Leite"'),
    ('"Anotá la producción de cada ordeñe."',
     '"Anote a produção de cada ordenha."'),
    ('"Registrar Ordeñe"',           '"Registrar Ordenha"'),
    ('"Ingresá los litros producidos en este ordeñe."',
     '"Informe os litros produzidos nesta ordenha."'),
    ('"Litros producidos"',          '"Litros produzidos"'),
    ('"Cuántos litros se obtuvieron en este ordeñe."',
     '"Quantos litros foram obtidos nesta ordenha."'),
    ('"Fecha y hora"',               '"Data e hora"'),
    ('"¿Cuándo se realizó el ordeñe?"', '"Quando foi realizada a ordenha?"'),
    ('"Observaciones"',              '"Observações"'),
    ('"Algo especial de este ordeñe (opcional)."',
     '"Algo especial desta ordenha (opcional)."'),
    ('"Primero elegí el animal."',   '"Primeiro escolha o animal."'),
    ('"Los litros deben ser mayor a 0."',
     '"Os litros devem ser maior que 0."'),
    ('f"✓ {litros.value:.1f} L registrados para {animal.value}."',
     'f"✓ {litros.value:.1f} L registrados para {animal.value}."'),
    ('"💾  Guardar Ordeñe"',         '"💾  Salvar Ordenha"'),
    ('"Producción por Animal"',      '"Produção por Animal"'),
    ('"Litros totales producidos por cada animal en los últimos 30 días."',
     '"Litros totais produzidos por cada animal nos últimos 30 dias."'),
    ('"Historial de Ordeñes"',       '"Histórico de Ordenhas"'),
    ('"Todavía no hay ordeñes registrados."',
     '"Ainda não há ordenhas registradas."'),
    ('"Usá el formulario de arriba para registrar el primero."',
     '"Use o formulário acima para registrar o primeiro."'),
    ('"Error al cargar producción."', '"Erro ao carregar produção."'),
    ('"Error al cargar historial."',  '"Erro ao carregar histórico."'),
    # ── Dietas page ───────────────────────────────────────────────────────
    ('"🥗 Dietas y Raciones"',        '"🥗 Dietas e Rações"'),
    ('"Consultá y gestioná los planes de alimentación del rodeo."',
     '"Consulte e gerencie os planos de alimentação do rebanho."'),
    ('"No se pudo cargar las dietas."',
     '"Não foi possível carregar as dietas."'),
    ('"Comparativa de Dietas"',      '"Comparativo de Dietas"'),
    ('"Energía (ENL) por dieta"',    '"Energia (ENL) por dieta"'),
    ('"Materia Seca Total (kg/día)"', '"Matéria Seca Total (kg/dia)"'),
    ('"Ingredientes de"',            '"Ingredientes de"'),
    ('"Ingrediente"',                '"Ingrediente"'),
    ('"kg/día"',                     '"kg/dia"'),
    ('"% MS"',                       '"% MS"'),
    ('"Energía ENL"',                '"Energia ENL"'),
    ('"Sin datos de dietas disponibles."',
     '"Sem dados de dietas disponíveis."'),
    ('"Error al cargar dietas."',    '"Erro ao carregar dietas."'),
    # ── Bodega page ───────────────────────────────────────────────────────
    ('"📦 Bodega / Insumos"',         '"📦 Estoque / Insumos"'),
    ('"Controlá el stock de alimentos, medicamentos y otros productos."',
     '"Controle o estoque de alimentos, medicamentos e outros produtos."'),
    ('"No se pudo cargar el inventario."',
     '"Não foi possível carregar o inventário."'),
    ('"Resumen de Stock"',            '"Resumo de Estoque"'),
    ('"crítico"',                     '"crítico"'),
    ('"medio"',                       '"médio"'),
    ('"ok"',                          '"ok"'),
    ('"Insumo"',                      '"Insumo"'),
    ('"Stock Actual (kg)"',           '"Estoque Atual (kg)"'),
    ('"Costo/kg ($)"',                '"Custo/kg (R$)"'),
    ('"Estado Stock"',                '"Status Estoque"'),
    ('"Actualizar Stock"',            '"Atualizar Estoque"'),
    ('"Elegí el insumo y el nuevo stock disponible."',
     '"Escolha o insumo e o novo estoque disponível."'),
    ('"Nuevo stock (kg)"',            '"Novo estoque (kg)"'),
    ('"Cuántos kg hay disponibles ahora."',
     '"Quantos kg estão disponíveis agora."'),
    ('"Nuevo costo/kg ($)"',          '"Novo custo/kg (R$)"'),
    ('"Precio actualizado por kilogramo (opcional)."',
     '"Preço atualizado por quilograma (opcional)."'),
    ('"Primero elegí un insumo."',    '"Primeiro escolha um insumo."'),
    ('f"✓ Stock de {insumo.value} actualizado a {stock_nuevo.value:.0f} kg."',
     'f"✓ Estoque de {insumo.value} atualizado para {stock_nuevo.value:.0f} kg."'),
    ('"💾  Actualizar Stock"',         '"💾  Atualizar Estoque"'),
    ('"Inventario Completo"',          '"Inventário Completo"'),
    ('"Error al cargar inventario."',  '"Erro ao carregar inventário."'),
    # ── Maquinaria page ───────────────────────────────────────────────────
    ('"🚜 Maquinaria"',                '"🚜 Maquinário"'),
    ('"Registrá y controlá las máquinas y sus mantenimientos."',
     '"Registre e controle as máquinas e suas manutenções."'),
    ('"No se pudo cargar la maquinaria."',
     '"Não foi possível carregar o maquinário."'),
    ('"Máquinas Registradas"',         '"Máquinas Cadastradas"'),
    ('"Agregar Máquina"',              '"Adicionar Máquina"'),
    ('"Registrá una nueva máquina o equipo de la granja."',
     '"Cadastre uma nova máquina ou equipamento da fazenda."'),
    ('"Nombre de la máquina"',         '"Nome da máquina"'),
    ('"Ej: Tractor 1, Ordeñadora A…"',
     '"Ex: Trator 1, Ordenhadeira A…"'),
    ('"Tipo"',                         '"Tipo"'),
    ('"Año"',                          '"Ano"'),
    ('"Año de fabricación o compra (opcional)."',
     '"Ano de fabricação ou compra (opcional)."'),
    ('"Estado"',                       '"Estado"'),
    ('"El nombre de la máquina es obligatorio."',
     '"O nome da máquina é obrigatório."'),
    ('f"✓ {nombre_m.value} agregada al registro."',
     'f"✓ {nombre_m.value} adicionada ao registro."'),
    ('"➕  Agregar Máquina"',           '"➕  Adicionar Máquina"'),
    ('"Registrar Mantenimiento"',       '"Registrar Manutenção"'),
    ('"Anotá un mantenimiento realizado o programado."',
     '"Anote uma manutenção realizada ou programada."'),
    ('"¿A qué máquina?"',              '"Qual máquina?"'),
    ('"Tipo de mantenimiento"',         '"Tipo de manutenção"'),
    ('"Técnico responsable"',           '"Técnico responsável"'),
    ('"Nombre o empresa (opcional)."',  '"Nome ou empresa (opcional)."'),
    ('"Costo ($)"',                     '"Custo (R$)"'),
    ('"Próximo mantenimiento"',         '"Próxima manutenção"'),
    ('"Fecha estimada del siguiente mantenimiento."',
     '"Data estimada da próxima manutenção."'),
    ('"Horas de uso"',                  '"Horas de uso"'),
    ('"Horas totales que lleva la máquina (opcional)."',
     '"Horas totais que a máquina tem (opcional)."'),
    ('"Primero elegí la máquina."',     '"Primeiro escolha a máquina."'),
    ('f"✓ Mantenimiento registrado para {maquina.value}."',
     'f"✓ Manutenção registrada para {maquina.value}."'),
    ('"💾  Guardar Mantenimiento"',     '"💾  Salvar Manutenção"'),
    ('"Historial de Mantenimientos"',   '"Histórico de Manutenções"'),
    ('"Todavía no hay mantenimientos registrados."',
     '"Ainda não há manutenções registradas."'),
    ('"Error al cargar historial."',    '"Erro ao carregar histórico."'),
    ('"Error al cargar máquinas."',     '"Erro ao carregar máquinas."'),
    # ── Reproducción page ─────────────────────────────────────────────────
    ('"🐣 Reproducción"',              '"🐣 Reprodução"'),
    ('"Controlá fertilizaciones y partos del rodeo."',
     '"Controle fertilizações e partos do rebanho."'),
    ('"No se pudo cargar los datos de reproducción."',
     '"Não foi possível carregar os dados de reprodução."'),
    ('"Próximos Partos"',              '"Próximos Partos"'),
    ('"¡En 3 días!"',                  '"Em 3 dias!"'),
    ('"Registrar Fertilización / Parto"', '"Registrar Fertilização / Parto"'),
    ('"Anotá una fertilización o el resultado de un parto."',
     '"Anote uma fertilização ou o resultado de um parto."'),
    ('"Tipo de evento"',               '"Tipo de evento"'),
    ('"Fertilización"',                '"Fertilização"'),
    ('"Tipo de fertilización"',        '"Tipo de fertilização"'),
    ('"Fecha estimada del parto"',     '"Data estimada do parto"'),
    ('"Se calcula automáticamente (283 días desde la fertilización)."',
     '"Calculada automaticamente (283 dias após a fertilização)."'),
    ('"Resultado del parto"',          '"Resultado do parto"'),
    ('"Sexo de la cría"',              '"Sexo da cria"'),
    ('"Macho"',                        '"Macho"'),
    ('"Hembra"',                       '"Fêmea"'),
    ('"No determinado"',               '"Não determinado"'),
    ('"Peso de la cría (kg)"',         '"Peso da cria (kg)"'),
    ('"Observaciones"',                '"Observações"'),
    ('"Primero elegí el tipo de evento."', '"Primeiro escolha o tipo de evento."'),
    ('f"✓ {tipo_ev.value} registrado para {animal.value}."',
     'f"✓ {tipo_ev.value} registrado para {animal.value}."'),
    ('"💾  Guardar Registro"',          '"💾  Salvar Registro"'),
    ('"Historial Reproductivo"',        '"Histórico Reprodutivo"'),
    ('"Todavía no hay registros reproductivos."',
     '"Ainda não há registros reprodutivos."'),
    ('"Error al cargar reproducción."', '"Erro ao carregar reprodução."'),
    ('"Sin partos próximos."',          '"Sem partos próximos."'),
    # ── Finanzas page ─────────────────────────────────────────────────────
    ('"💰 Finanzas"',                   '"💰 Finanças"'),
    ('"Registrá ingresos y egresos de la granja."',
     '"Registre receitas e despesas da fazenda."'),
    ('"No se pudo cargar los datos financieros."',
     '"Não foi possível carregar os dados financeiros."'),
    ('"Resumen del Mes"',               '"Resumo do Mês"'),
    ('"Ingresos"',                      '"Receitas"'),
    ('"Egresos"',                       '"Despesas"'),
    ('"Balance"',                       '"Balanço"'),
    ('"Registrar Movimiento"',          '"Registrar Movimento"'),
    ('"Anotá un ingreso o un gasto de la granja."',
     '"Anote uma receita ou uma despesa da fazenda."'),
    ('"Tipo"',                          '"Tipo"'),
    ('"Ingreso"',                       '"Receita"'),
    ('"Egreso"',                        '"Despesa"'),
    ('"Categoría"',                     '"Categoria"'),
    ('"Monto ($)"',                     '"Valor (R$)"'),
    ('"El monto debe ser mayor a 0."',
     '"O valor deve ser maior que 0."'),
    ('f"✓ {tipo_mov.value} de ${monto.value:,.0f} registrado."',
     'f"✓ {tipo_mov.value} de R${monto.value:,.0f} registrado."'),
    ('"💾  Guardar Movimiento"',         '"💾  Salvar Movimento"'),
    ('"Historial Financiero"',           '"Histórico Financeiro"'),
    ('"Todavía no hay movimientos registrados."',
     '"Ainda não há movimentos registrados."'),
    ('"Error al cargar finanzas."',     '"Erro ao carregar finanças."'),
    ('"Balance Mensual"',               '"Balanço Mensal"'),
    # ── Empleados page ────────────────────────────────────────────────────
    ('"👷 Empleados"',                  '"👷 Funcionários"'),
    ('"Administrá el personal de la granja y los pagos."',
     '"Gerencie o pessoal da fazenda e os pagamentos."'),
    ('"No se pudo cargar los empleados."',
     '"Não foi possível carregar os funcionários."'),
    ('"Resumen del Personal"',          '"Resumo do Pessoal"'),
    ('"activos"',                       '"ativos"'),
    ('"Total mensual estimado"',        '"Total mensal estimado"'),
    ('"Agregar Empleado"',              '"Adicionar Funcionário"'),
    ('"Registrá un nuevo integrante del equipo."',
     '"Cadastre um novo membro da equipe."'),
    ('"Nombre completo"',               '"Nome completo"'),
    ('"Nombre y apellido del empleado."',
     '"Nome e sobrenome do funcionário."'),
    ('"Cargo"',                         '"Cargo"'),
    ('"Sueldo base ($)"',               '"Salário base (R$)"'),
    ('"Remuneración mensual acordada."',
     '"Remuneração mensal acordada."'),
    ('"Teléfono"',                      '"Telefone"'),
    ('"Número de contacto (opcional)."',
     '"Número de contato (opcional)."'),
    ('"Fecha de ingreso"',              '"Data de admissão"'),
    ('"El nombre del empleado es obligatorio."',
     '"O nome do funcionário é obrigatório."'),
    ('f"✓ {nombre_emp.value} fue agregado como {cargo.value}."',
     'f"✓ {nombre_emp.value} foi adicionado como {cargo.value}."'),
    ('"➕  Agregar Empleado"',           '"➕  Adicionar Funcionário"'),
    ('"Lista de Empleados"',             '"Lista de Funcionários"'),
    ('"Todavía no hay empleados registrados."',
     '"Ainda não há funcionários cadastrados."'),
    ('"Error al cargar empleados."',    '"Erro ao carregar funcionários."'),
    ('"💸 Registrar un Pago"',           '"💸 Registrar um Pagamento"'),
    ('"Registrá sueldos, adelantos, bonos o liquidaciones."',
     '"Registre salários, adiantamentos, bônus ou rescisões."'),
    ('"¿A qué empleado?"',              '"Qual funcionário?"'),
    ('"Tipo de pago"',                  '"Tipo de pagamento"'),
    ('"Monto ($)"',                     '"Valor (R$)"'),
    ('"Fecha del pago"',                '"Data do pagamento"'),
    ('"Ej: Sueldo mayo 2026, Adelanto quincena, Premio productividad…"',
     '"Ex: Salário maio 2026, Adiantamento quinzena, Prêmio produtividade…"'),
    ('"Detalle del pago…"',             '"Detalhe do pagamento…"'),
    ('"Primero elegí el empleado."',    '"Primeiro escolha o funcionário."'),
    ('"El monto debe ser mayor a 0."',
     '"O valor deve ser maior que 0."'),
    ('f"✓ {tipo_pago.value} de ${monto_pago.value:,.0f} registrado para {emp_sel.value}."',
     'f"✓ {tipo_pago.value} de R${monto_pago.value:,.0f} registrado para {emp_sel.value}."'),
    ('"💾  Registrar Pago"',             '"💾  Registrar Pagamento"'),
    ('"Historial de Pagos"',             '"Histórico de Pagamentos"'),
    ('"Todavía no hay pagos registrados."',
     '"Ainda não há pagamentos registrados."'),
    ('"Error al cargar pagos."',        '"Erro ao carregar pagamentos."'),
    # ── Reportes page ─────────────────────────────────────────────────────
    ('"📊 Reportes"',                   '"📊 Relatórios"'),
    ('"Resúmenes y análisis de todas las áreas de tu granja."',
     '"Resumos e análises de todas as áreas da sua fazenda."'),
    ('"🥛 Leche"',                      '"🥛 Leite"'),
    ('"💊 Salud"',                      '"💊 Saúde"'),
    ('"🐣 Reproducción"',               '"🐣 Reprodução"'),
    ('"💰 Finanzas"',                   '"💰 Finanças"'),
    ('"👷 Empleados"',                  '"👷 Funcionários"'),
    ('"🚜 Maquinaria"',                 '"🚜 Maquinário"'),
    ('"Producción diaria — últimas 4 semanas"',
     '"Produção diária — últimas 4 semanas"'),
    ('"Litros totales ordeñados cada día."',
     '"Litros totais ordenhados por dia."'),
    ('"Producción por grupo"',          '"Produção por grupo"'),
    ('"Litros totales acumulados por cada grupo de alimentación."',
     '"Litros totais acumulados por grupo de alimentação."'),
    ('"🏆 Top 10 vacas más productivas"', '"🏆 Top 10 vacas mais produtivas"'),
    ('"📅 Resumen mensual"',             '"📅 Resumo mensal"'),
    ('"Eventos sanitarios por tipo"',   '"Eventos sanitários por tipo"'),
    ('"Cantidad de registros por categoría."',
     '"Quantidade de registros por categoria."'),
    ('"Atenciones y costos mensuales"', '"Atendimentos e custos mensais"'),
    ('"Evolución del número de atenciones y del gasto veterinario."',
     '"Evolução do número de atendimentos e do gasto veterinário."'),
    ('"🏥 Top 10 animales con más atenciones"',
     '"🏥 Top 10 animais com mais atendimentos"'),
    ('"Fertilizaciones y partos por mes"',
     '"Fertilizações e partos por mês"'),
    ('"Comparativa mensual de eventos reproductivos."',
     '"Comparativo mensal de eventos reprodutivos."'),
    ('"Resultados de partos"',          '"Resultados de partos"'),
    ('"Tipo de fertilización"',         '"Tipo de fertilização"'),
    ('"Próximos partos (30 días)"',     '"Próximos partos (30 dias)"'),
    ('"Ingresos vs Egresos por mes"',   '"Receitas vs Despesas por mês"'),
    ('"Evolución financiera mensual."', '"Evolução financeira mensal."'),
    ('"Egresos por categoría"',         '"Despesas por categoria"'),
    ('"Distribución del gasto."',       '"Distribuição dos gastos."'),
    ('"📋 Fuentes de ingreso"',          '"📋 Fontes de receita"'),
    ('"📅 Resultado mensual"',           '"📅 Resultado mensal"'),
    ('"Nómina mensual"',                '"Folha de pagamento mensal"'),
    ('"Total pagado por mes."',         '"Total pago por mês."'),
    ('"Tipos de pago"',                 '"Tipos de pagamento"'),
    ('"Distribución de pagos realizados."',
     '"Distribuição de pagamentos realizados."'),
    ('"💵 Total pagado por empleado"',   '"💵 Total pago por funcionário"'),
    ('"Costo de mantenimiento por máquina"',
     '"Custo de manutenção por máquina"'),
    ('"Total gastado en mantenimientos para cada equipo."',
     '"Total gasto em manutenções para cada equipamento."'),
    ('"Tipo de mantenimiento"',         '"Tipo de manutenção"'),
    ('"Historial por máquina"',         '"Histórico por máquina"'),
    ('"Mantenimientos por mes"',        '"Manutenções por mês"'),
    # ── Ficha individual ──────────────────────────────────────────────────
    ('"Animal no encontrado."',         '"Animal não encontrado."'),
    ('"← Volver"',                      '"← Voltar"'),
    ('f"Grupo: {info[\'grupo\']}  •  Estado: {info[\'estado\']}  •  {info[\'dias_en_granja\']} días en la granja"',
     'f"Grupo: {info[\'grupo\']}  •  Estado: {info[\'estado\']}  •  {info[\'dias_en_granja\']} dias na fazenda"'),
    ('"🥛 Total producido"',             '"🥛 Total produzido"'),
    ('"acumulado histórico"',           '"acumulado histórico"'),
    ('"📊 Promedio/ordeñe"',             '"📊 Média/ordenha"'),
    ('"por sesión de ordeñe"',          '"por sessão de ordenha"'),
    ('"💊 Eventos de salud"',            '"💊 Eventos de saúde"'),
    ('"registros encontrados"',         '"registros encontrados"'),
    ('"🐣 Eventos reproductivos"',       '"🐣 Eventos reprodutivos"'),
    ('"fertilizaciones/partos"',        '"fertilizações/partos"'),
    ('"📈 Producción — últimos 30 días"',
     '"📈 Produção — últimos 30 dias"'),
    ('"Litros por día de ordeñe."',     '"Litros por dia de ordenha."'),
    ('"Sin registros de producción en los últimos 30 días."',
     '"Sem registros de produção nos últimos 30 dias."'),
    ('"💊 Historial Sanitario"',         '"💊 Histórico Sanitário"'),
    ('"Sin eventos de salud registrados."',
     '"Sem eventos de saúde registrados."'),
    ('"🐣 Historial Reproductivo"',      '"🐣 Histórico Reprodutivo"'),
    ('"Sin eventos reproductivos registrados."',
     '"Sem eventos reprodutivos registrados."'),
    ('"Error al cargar la ficha:"',     '"Erro ao carregar a ficha:"'),
    # ── Títulos en header ─────────────────────────────────────────────────
    ('"🐄 Dairy Farm Pro"',  '"🐄 Dairy Farm Pro"'),  # keep same
    # ── ui.run title ──────────────────────────────────────────────────────
    ('title="Dairy Farm Pro"', 'title="Dairy Farm Pro"'),
    # ── SQL column aliases (display only) ─────────────────────────────────
    ('AS "Nombre / Etiqueta"',   'AS "Nome / Etiqueta"'),
    ('AS "Grupo"',               'AS "Grupo"'),
    ('AS "Estado"',              'AS "Estado"'),
    ('AS "Fecha"',               'AS "Data"'),
    ('AS "Tipo"',                'AS "Tipo"'),
    ('AS "Descripción"',         'AS "Descrição"'),
    ('AS "Veterinario"',         'AS "Veterinário"'),
    ('AS "Costo $"',             'AS "Custo R$"'),
    ('AS "Animal"',              'AS "Animal"'),
    ('AS "Litros"',              'AS "Litros"'),
    ('AS "Fecha/Hora"',          'AS "Data/Hora"'),
    ('AS "Observaciones"',       'AS "Observações"'),
    ('AS "Nombre"',              'AS "Nome"'),
    ('AS "Año"',                 'AS "Ano"'),
    ('AS "Tipo Máquina"',        'AS "Tipo Máquina"'),
    ('AS "Técnico"',             'AS "Técnico"'),
    ('AS "Próximo Mant."',       'AS "Próx. Manutenção"'),
    ('AS "Horas Uso"',           'AS "Horas Uso"'),
    ('AS "Fertilización"',       'AS "Fertilização"'),
    ('AS "Parto esperado"',      'AS "Parto esperado"'),
    ('AS "Resultado"',           'AS "Resultado"'),
    ('AS "Empleado"',            'AS "Funcionário"'),
    ('AS "Cargo"',               'AS "Cargo"'),
    ('AS "Sueldo Base $"',       'AS "Salário Base R$"'),
    ('AS "Teléfono"',            'AS "Telefone"'),
    ('AS "Ingreso"',             'AS "Admissão"'),
    ('AS "Monto $"',             'AS "Valor R$"'),
    ('AS "Categoría"',           'AS "Categoria"'),
    ('AS "Total Litros"',        'AS "Total Litros"'),
    ('AS "Promedio por ordeñe"', 'AS "Média por ordenha"'),
    ('AS "Vaca"',                'AS "Vaca"'),
    ('AS "Mes"',                 'AS "Mês"'),
    ('AS "Litros totales"',      'AS "Litros totais"'),
    ('AS "Vacas registradas"',   'AS "Vacas registradas"'),
    ('AS "Último Mant."',        'AS "Última Manutenção"'),
    ('AS "Mantenimientos"',      'AS "Manutenções"'),
    ('AS "Costo Total $"',       'AS "Custo Total R$"'),
    ('AS "Cantidad"',            'AS "Quantidade"'),
    ('AS "Costo Total $"',       'AS "Custo Total R$"'),
]

def translate_main():
    path = "app/main.py"
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    for old, new in TEXT_MAP:
        content = content.replace(old, new)

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"OK: main.py traduzido ({len(TEXT_MAP)} substituições aplicadas).")


# ── Migração do banco ─────────────────────────────────────────────────────────
DB_UPDATES = [
    # tabla_vacas
    ("UPDATE tabla_vacas SET estado='ativa'   WHERE estado='activa'",   None),
    ("UPDATE tabla_vacas SET estado='inativa' WHERE estado='inactiva'", None),
    # tabla_salud
    ("UPDATE tabla_salud SET tipo_evento='Vacinação'         WHERE tipo_evento='Vacunación'",         None),
    ("UPDATE tabla_salud SET tipo_evento='Controle rotineiro' WHERE tipo_evento='Control rutinario'", None),
    ("UPDATE tabla_salud SET tipo_evento='Tratamento'        WHERE tipo_evento='Tratamiento'",         None),
    ("UPDATE tabla_salud SET tipo_evento='Doença'            WHERE tipo_evento='Enfermedad'",          None),
    ("UPDATE tabla_salud SET tipo_evento='Parto assistido'   WHERE tipo_evento='Parto asistido'",      None),
    ("UPDATE tabla_salud SET tipo_evento='Cirurgia'          WHERE tipo_evento='Cirugía'",             None),
    # tabla_maquinaria tipo
    ("UPDATE tabla_maquinaria SET tipo='Trator'        WHERE tipo='Tractor'",    None),
    ("UPDATE tabla_maquinaria SET tipo='Ordenhadeira'  WHERE tipo='Ordeñadora'", None),
    ("UPDATE tabla_maquinaria SET tipo='Compressor'    WHERE tipo='Compresor'",  None),
    ("UPDATE tabla_maquinaria SET tipo='Gerador'       WHERE tipo='Generador'",  None),
    ("UPDATE tabla_maquinaria SET tipo='Carregadeira'  WHERE tipo='Cargadora'",  None),
    ("UPDATE tabla_maquinaria SET tipo='Outro'         WHERE tipo='Otro'",       None),
    # tabla_maquinaria estado
    ("UPDATE tabla_maquinaria SET estado='Operacional'    WHERE estado='Operativa'",         None),
    ("UPDATE tabla_maquinaria SET estado='Em manutenção'  WHERE estado='En mantenimiento'",  None),
    ("UPDATE tabla_maquinaria SET estado='Fora de serviço' WHERE estado='Fuera de servicio'",None),
    # tabla_mantenimiento tipo_mantencion
    ("UPDATE tabla_mantenimiento SET tipo_mantencion='Corretivo'    WHERE tipo_mantencion='Correctivo'",      None),
    ("UPDATE tabla_mantenimiento SET tipo_mantencion='Troca de óleo' WHERE tipo_mantencion='Cambio de aceite'",None),
    ("UPDATE tabla_mantenimiento SET tipo_mantencion='Revisão geral' WHERE tipo_mantencion='Revisión general'",None),
    ("UPDATE tabla_mantenimiento SET tipo_mantencion='Reparo'        WHERE tipo_mantencion='Reparación'",      None),
    ("UPDATE tabla_mantenimiento SET tipo_mantencion='Calibração'    WHERE tipo_mantencion='Calibración'",     None),
    # tabla_reproduccion tipo_evento
    ("UPDATE tabla_reproduccion SET tipo_evento='Fertilização' WHERE tipo_evento='Fertilización'", None),
    ("UPDATE tabla_reproduccion SET tipo_evento='Parto'        WHERE tipo_evento='Parto'",         None),
    # tabla_reproduccion tipo_fertilizacion
    ("UPDATE tabla_reproduccion SET tipo_fertilizacion='Inseminação Artificial' WHERE tipo_fertilizacion='Inseminación Artificial'", None),
    # tabla_reproduccion resultado_parto
    ("UPDATE tabla_reproduccion SET resultado_parto='Bem-sucedido' WHERE resultado_parto='Exitoso'",    None),
    ("UPDATE tabla_reproduccion SET resultado_parto='Cria morta'   WHERE resultado_parto='Cría muerta'",None),
    # tabla_finanzas tipo
    ("UPDATE tabla_finanzas SET tipo='Receita' WHERE tipo='Ingreso'", None),
    ("UPDATE tabla_finanzas SET tipo='Despesa' WHERE tipo='Egreso'",  None),
    # tabla_finanzas categoria
    ("UPDATE tabla_finanzas SET categoria='Venda de leite'         WHERE categoria='Venta de leche'",           None),
    ("UPDATE tabla_finanzas SET categoria='Venda de animais'       WHERE categoria='Venta de animales'",        None),
    ("UPDATE tabla_finanzas SET categoria='Subsídio ou apoio estatal' WHERE categoria='Subsidio o ayuda estatal'",None),
    ("UPDATE tabla_finanzas SET categoria='Outra receita'          WHERE categoria='Otro ingreso'",             None),
    ("UPDATE tabla_finanzas SET categoria='Alimentação e insumos'  WHERE categoria='Alimentación e insumos'",   None),
    ("UPDATE tabla_finanzas SET categoria='Veterinário e saúde animal' WHERE categoria='Veterinario y salud animal'",None),
    ("UPDATE tabla_finanzas SET categoria='Manutenção de maquinário' WHERE categoria='Mantenimiento de maquinaria'",None),
    ("UPDATE tabla_finanzas SET categoria='Mão de obra'            WHERE categoria='Mano de obra'",             None),
    ("UPDATE tabla_finanzas SET categoria='Combustível'            WHERE categoria='Combustible'",              None),
    ("UPDATE tabla_finanzas SET categoria='Serviços (luz, água, gás)' WHERE categoria='Servicios (luz, agua, gas)'",None),
    ("UPDATE tabla_finanzas SET categoria='Outros gastos'          WHERE categoria='Otros gastos'",             None),
    # tabla_empleados cargo
    ("UPDATE tabla_empleados SET cargo='Ordenhador/a'           WHERE cargo='Ordeñador/a'",                          None),
    ("UPDATE tabla_empleados SET cargo='Tratorista'             WHERE cargo='Tractorista'",                          None),
    ("UPDATE tabla_empleados SET cargo='Resp. por alimentação'  WHERE cargo='Encargado/a de alimentación'",          None),
    ("UPDATE tabla_empleados SET cargo='Resp. por sanidade'     WHERE cargo='Encargado/a de sanidad'",               None),
    ("UPDATE tabla_empleados SET cargo='Veterinário/a de campo' WHERE cargo='Veterinario/a de campo'",               None),
    ("UPDATE tabla_empleados SET cargo='Trabalhador rural'      WHERE cargo='Peón rural'",                           None),
    # tabla_empleados estado
    ("UPDATE tabla_empleados SET estado='ativo'   WHERE estado='activo'",   None),
    ("UPDATE tabla_empleados SET estado='inativo' WHERE estado='inactivo'", None),
    # tabla_pagos tipo
    ("UPDATE tabla_pagos SET tipo='Salário'      WHERE tipo='Sueldo'",      None),
    ("UPDATE tabla_pagos SET tipo='Adiantamento' WHERE tipo='Adelanto'",    None),
    ("UPDATE tabla_pagos SET tipo='Bônus'        WHERE tipo='Bono'",        None),
    ("UPDATE tabla_pagos SET tipo='Rescisão'     WHERE tipo='Liquidación'", None),
]

def migrate_db():
    conn = psycopg2.connect(**DB_CONFIG)
    cur  = conn.cursor()
    total = 0
    for sql, params in DB_UPDATES:
        try:
            cur.execute(sql, params)
            total += cur.rowcount
        except Exception as e:
            print(f"  ERRO: {sql[:60]}… → {e}")
    conn.commit()
    cur.close(); conn.close()
    print(f"OK: banco migrado ({total} linhas atualizadas).")


if __name__ == "__main__":
    translate_main()
    migrate_db()
